"""migrate_event_invitee_categories

Revision ID: 06468953268d
Revises: a2fd3b0e28ea
Create Date: 2026-01-26 09:47:33.012910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06468953268d'
down_revision = 'a2fd3b0e28ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_invitees_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
    # Data Migration
    bind = op.get_bind()
    meta = sa.MetaData()
    meta.bind = bind
    
    categories_t = sa.Table('categories', meta, autoload_with=bind)
    event_invitees_t = sa.Table('event_invitees', meta, autoload_with=bind)
    
    # Map name -> id
    cat_map = {}
    rows = bind.execute(sa.select(categories_t.c.id, categories_t.c.name)).fetchall()
    for r in rows:
        cat_map[r[1]] = r[0]
        
    for name, cat_id in cat_map.items():
        bind.execute(
            event_invitees_t.update().where(event_invitees_t.c.category == name).values(category_id=cat_id)
        )

    with op.batch_alter_table('event_invitees', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_invitees_category_id'))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
