"""Add email and full_name to users

Revision ID: 16afec26554a
Revises: 
Create Date: 2026-01-23 11:06:43.728415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16afec26554a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # First add email as nullable
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
    
    # Update existing users with a default email based on username
    op.execute("UPDATE users SET email = username || '@example.com' WHERE email IS NULL")
    op.execute("UPDATE users SET full_name = username WHERE full_name IS NULL")
    
    # Now make email non-nullable and add unique index
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
