"""add_default_plus_one_to_invitee

Revision ID: 4a70eab94824
Revises: 06468953268d
Create Date: 2026-01-26 14:00:21.935292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a70eab94824'
down_revision = '06468953268d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_plus_one', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.drop_column('default_plus_one')

    # ### end Alembic commands ###
