"""add_categories_table_and_migrate_data

Revision ID: a2fd3b0e28ea
Revises: d51d50965d54
Create Date: 2026-01-26 09:44:35.796222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fd3b0e28ea'
down_revision = 'd51d50965d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create categories table if it doesn't exist (handling the weird state)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'categories' not in tables:
        op.create_table('categories',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
    else:
        # If it exists, ensure is_active exists
        columns = [c['name'] for c in inspector.get_columns('categories')]
        if 'is_active' not in columns:
            with op.batch_alter_table('categories', schema=None) as batch_op:
                batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # Add category_id to invitees
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invitees_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitees_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # DATA MIGRATION
    # 1. Populate Categories
    meta = sa.MetaData()
    meta.bind = bind
    
    # Define tables for sql execution
    categories_t = sa.Table('categories', meta, autoload_with=bind)
    invitees_t = sa.Table('invitees', meta, autoload_with=bind)
    
    # Insert categories
    from datetime import datetime
    now = datetime.utcnow()
    
    # Check if we need to insert
    existing_cats = bind.execute(sa.select(categories_t.c.name)).fetchall()
    existing_names = [r[0] for r in existing_cats]
    
    cats_to_insert = []
    if 'White' not in existing_names:
        cats_to_insert.append({'name': 'White', 'is_active': True, 'created_at': now, 'updated_at': now})
    if 'Gold' not in existing_names:
        cats_to_insert.append({'name': 'Gold', 'is_active': True, 'created_at': now, 'updated_at': now})
        
    if cats_to_insert:
        op.bulk_insert(categories_t, cats_to_insert)
        
    # 2. Update Invitees
    # Map 'White' -> id, 'Gold' -> id
    cat_map = {}
    rows = bind.execute(sa.select(categories_t.c.id, categories_t.c.name)).fetchall()
    for r in rows:
        cat_map[r[1]] = r[0] # name -> id
        
    # Run update for each category
    for name, cat_id in cat_map.items():
        # Update invitees where category == name
        bind.execute(
            invitees_t.update().where(invitees_t.c.category == name).values(category_id=cat_id)
        )

    # Clean up old column
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invitees_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_invitees_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
