"""Make inviter_group_id nullable

Revision ID: ad900b0b75b4
Revises: f8e2a3c4d567
Create Date: 2026-01-28 12:13:24.252131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad900b0b75b4'
down_revision = 'f8e2a3c4d567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.drop_column('default_plus_one')

    with op.batch_alter_table('inviters', schema=None) as batch_op:
        batch_op.alter_column('inviter_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('inviters_inviter_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'inviter_groups', ['inviter_group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inviters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inviters_inviter_group_id_fkey'), 'inviter_groups', ['inviter_group_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('inviter_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_plus_one', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
