"""Add inviter model and update schema

Revision ID: c9663ec139fc
Revises: 16afec26554a
Create Date: 2026-01-24 13:58:14.812047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9663ec139fc'
down_revision = '16afec26554a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_event_invitees_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_foreign_key(None, 'inviters', ['inviter_id'], ['id'])
        batch_op.drop_column('invitation_class')

    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('inviter_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invitees_inviter_group_id'), ['inviter_group_id'], unique=False)
        batch_op.create_foreign_key(None, 'inviter_groups', ['inviter_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invitees_inviter_group_id'))
        batch_op.drop_column('inviter_group_id')
        batch_op.drop_column('category')

    with op.batch_alter_table('event_invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_invitees_inviter_id'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('inviter_id')

    # ### end Alembic commands ###
